### PR TITLE
Update dependencies and license

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

We changed dependencies of the pypi package (igraph -> networkx) so that we can update the license GPL -> BSD

closes #1

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
Hi @goanpeca and/or @jaimergp ,

we updated dependencies and the license of this napari plugin. Hence, I took the PR-branch generated by the bot and updated license and depencies here as well. I'm now wondering, can I just merge this, or do I need to send another PR somewhere else? Or is a formal review from somebody else necessary?

Thanks!

Best,
Robert

**Comment by goanpeca** [comment]
>I'm now wondering, can I just merge this, or do I need to send another PR somewhere else? Or is a formal review from somebody else necessary?

Hi @haesleinhuepf first we need to make sure that tests pass :) 

```
import: 'napari_workflow_inspector'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/napari-workflow-inspector_1646553966882/test_tmp/run_test.py", line 5, in <module>
    import igraph
ModuleNotFoundError: No module named 'igraph'
import: 'igraph'
```

**Comment by goanpeca** [comment]
Also @haesleinhuepf you should be able to update/edit the files of that other PR directly on github 

https://github.com/regro-cf-autotick-bot/napari-workflow-inspector-feedstock/edit/0.2.0_h8bccc9/recipe/meta.yaml?pr=%2Fconda-forge%2Fnapari-workflow-inspector-feedstock%2Fpull%2F1

So I would make the update there, and close this one.

**Comment by haesleinhuepf** [comment]
Thanks for the feedback, @goanpeca ! I modified the [other PR](https://github.com/conda-forge/napari-workflow-inspector-feedstock/pull/1/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9a). Let's see if the tests pass there ;-)

**Pull request closed without merging**
